apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: petstore
  namespace: external-systems
  description: Petstore
  annotations:
    backstage.io/kubernetes-label-selector: 'app=pets-rest-api'
    # backstage.io/kubernetes-id: value
spec:
  type: service
  lifecycle: experimental
  owner: group:pet-managers
  providesApis:
    - petstore-api
    - internal/streetlights
    - hello-world